variables:
  pytest_args:
    description: "Параметры pytest (например ссылка на сьют относительно root --> tests/test_e2e.py"

stages:
  - test

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $pytest_args == ""
      when: never
    - when: on_success
  before_script:
    - rm -rf ./allure-results
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
  script:
    - pytest -s --alluredir ./allure-results $pytest_args
